### ISSUE TITLE
MikroORM v4

### ISSUE THREAD

**Issue by B4nan** [mikro-orm/mikro-orm#527]
## Progress

- [x] Single table inheritance (#33, #503)
- [x] Allow adding items to not initialized collections (#489)
- [x] Use absolute path to entity file in static MetadataStorage keys (fix for 'Multiple property decorators' validation issues) (#488)
- [x] Embedded entities (allow in-lining child entity into parent one with prefixed keys) (#514)
- [x] Add support for Node.js 14 (#522)
- [x] Support subqueries in QB (#525)
- [x] Nested conditions in `qb.update()` queries via subqueries (#319, #537)
- [x] Nested conditions in `em.remove()` via subqueries (#492, #538)
- [x] Use custom errors for specific cases (unique constraint violation, db not accessible, ...) (#539, #611)
- [x] Paginator helper or something similar ([doctrine docs](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html)) (#544)
- [x] Add `groupBy` and `distinct` to `FindOptions` and `FindOneOptions`
- [x] Support computed properties via `@Formula()` decorator (#553)
- [x] Allow the use of TS path mapping (#554)
- [x] Add custom types for blob, array, json (#476)
- [x] Pass entity instance as parameter in `onCreate` and `onUpdate` (#564)
- [x] Cache metadata only with ts-morph provider (#569)
- [x] Allow using different primary key types than ObjectId in mongo driver (#349, #568)
- [x] Lazy scalar properties (allow having props that won't be loaded by default, but can be populated) (#427, #585)
- [x] Support for alternative loading strategies (#440, #556, #600)
- [x] Support external hooks when using EntitySchema (hooks outside of entity) (#516, #614)
- [x] Execute hooks via `EventManager` (adds `EventArgs` to hook params) (#622, #623)
- [x] Add support for flush events (allows to modify change sets) (#637, #642)
- [x] Use `.d.ts` files in `TsMorphMetadataProvider` (#616)
- [x] Ensure correct order of tables in schema generator (#617)
- [x] Ability to specify entities glob instead of entitiesDir glob (#605, #618) 
- [x] Refactor internal dependencies to support Yarn PnP (#645)
- [x] Association scopes/filters ([hibernate docs](https://docs.jboss.org/hibernate/orm/3.6/reference/en-US/html/filters.html)) (#385, #663)
- [x] Add support for entity and property comments (#668)
- [x] Add `driver.nativeInsertMany()` method (#688)
- [x] Static checking of population (#214, #691)
- [x] Add `em.begin/commit/rollback` methods (#717)
- [x] Bulk deletes (#757)
- [x] Refactor merging to allow querying by custom type (#800)

## Breaking changes

- [x] Require node 10+
- [x] Require TS 3.7 or newer
- [x] Split into multiple packages (core, driver packages, TS support, SQL support, CLI) (#475)
- [x] Remove `autoFlush` option (#439)
- [x] Drop default value for platform `type` (currently defaults to `mongodb`)
- [x] Remove `IdEntity/UuidEntity/MongoEntity` interfaces
- [x] Use `jsonb` as default for object columns in postgres
- [x] Do not define internal methods like `init` directly on the entity prototype (#506)
- [x] Support multiple M:N with same properties without manually specifying `pivotTable`
- [x] Type-safe custom `Type` class (#540)
- [x] Change behaviour of property `default`, add `defaultRaw` (#546)
- [x] Remove `flush` parameter, allow fluid `em.persist().flush()` calls instead (#648)
- [x] Require entity instance in `em.remove()`, remove `em.removeEntity()` (#648)

Summary (WIP): https://github.com/mikro-orm/mikro-orm/blob/master/docs/docs/upgrading-v3-to-v4.md
Example migration: https://github.com/mikro-orm/nestjs-realworld-example-app/commit/89ec53ca678f9ef0c1538ff9fc14448a016daa72

## Planned release

The aim is to have late beta or RC version at the end of ~may~ june, and release the full version during ~june~ july. 
You can track the progress also in PR #515. 
Some features might be postponed for some 4.x release.

**Comment by B4nan** [comment]
First alpha version is out on NPM, under the `next` tag.

https://www.npmjs.com/package/mikro-orm/v/4.0.0-alpha.0

Some notes about breaking changes are here (plus in the issues linked in the OP):

https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/upgrading-v3-to-v4.md

**Comment by dystopiandev** [comment]
I think you missed something.
`ENOENT: no such file or directory, chmod '.../node_modules/mikro-orm/dist/cli.js'`

**Comment by kibertoad** [comment]
@dystopiandev @B4nan I've opened #586 to prevent publishing non-built project in the future.

**Comment by B4nan** [comment]
@kibertoad Nope, that is now what happened, I did build the project before publishing. There is no `mikro-orm/dist/cli.js` file anymore, its in the CLI package...

**Comment by B4nan** [comment]
@dystopiandev trying this out myself and it works ok for me, how did you get to that error? at least `npx mikro-orm debug` works fine for me.

all I did was to upgrade `mikro-orm` package and installed `@mikro-orm/postgresql` (and removed `pg` from deps, as that is now part of `@mikro-orm/postgresql`)

**Comment by dystopiandev** [comment]
@B4nan I ran `npm i mikro-orm@next`

**Comment by B4nan** [comment]
Well but that definitely does not cause such error, right? So what CLI command did you use to get it? (exact one, e.g. did you use `npx`, or something like that? maybe some npm cache?)

**Comment by dystopiandev** [comment]
`npm i mikro-orm@next`. Nothing else.

**Comment by B4nan** [comment]
I am using `yarn` so this might be some weirdness of how `npm` cli works. Anyway, I already removed the `bin` part from the `mikro-orm` meta package, so it should be fine in next versions.

**Comment by rhyek** [comment]
I tried installing yesterday and got the same error.

**Comment by B4nan** [comment]
Just released `4.0.0-alpha.2` that should be addressing the problem.

**Comment by gperdomor** [comment]
@B4nan any plans to use @mysql/xdevapi for fully compatibility to MySQL 8?

**Comment by B4nan** [comment]
How is that about MySQL 8 compatibility? Never seen that before, but the readme states its basically NoSQL api for mysql 8. I am not aware of any issues with MySQL compatibility, can you be more specific?

**Comment by gperdomor** [comment]
@B4nan `typeorm` uses `mysql` package which have some issues created in their repository related to incompatibilities with MySQL 8, `mikro-orm` use `mysql2`, which is some kind of sibling of mysql and is api compatible, both project will converge in one unique project under `mysqljs` organization

> MySQL2 team is working together with mysqljs/mysql team to factor out shared code and move it under mysqljs organisation

In the other hand, `@mysql/xdevapi` is a new official NodeJS connector designed for MySQL 8 and supported by Oracle, and work with tables too, not only with NoSQL features, check this https://dev.mysql.com/doc/x-devapi-userguide/en/sql-crud-functions.html#table-insert

`@mysql/xdevapi` implements the X Protocol and use protocol buffers, so is more faster in theory is faster

Since this is a major release, is a good opportunity to explore this new package and  The problem here is, using @mysql/xdevapi implies drop MySQL <8 support, but again, is a major release so breaking changes are allowed

**Comment by B4nan** [comment]
I still don't see any reason to do this. I invested lots of time to build the SQL driver layer on top of knex, I have no plans to change that, definitely not because "it might be faster in theory" :]. 

You can create custom driver yourself to try, if it will be actually faster, will be happy to merge that (as additional driver, not a replacement to the current MySQL one), but no plans to work on that on my side. Keep in mind that this will be huge amount of work, as you won't be able to reuse anything from current `AbstractSqlDriver` (you would have to rebuild also schema generator support, as that works via SQL queries).

I am still waiting for the explanation of what compatibility issues need to be addressed with MySQL 8 as I am not aware of any. 

> and work with tables too, not only with NoSQL features

You are mixing terms here. This is purely about the API (executing string SQL queries vs calling dedicated methods). The underlying database is still the same MySQL that you can use by executing string queries now.

**Comment by gperdomor** [comment]
It was just a proposal, no need to be offensive, this is a community and is good receive suggestions, and things like `I invested lots of time to build the SQL driver layer on top of knex, I have no plans to change that, definitely not because "it might be faster in theory" :]` sound a little out of place, not need to be angry...

But don't worry, if you are building on top of knexjs then you aren't using mysql/mysql2 directly, so in that case is knexjs which need to made the change, sorry for putting this suggestion in the wrong repo...

> I am still waiting for the explanation of what compatibility issues need to be addressed with MySQL 8 as I am not aware of any.

https://github.com/mysqljs/mysql/issues?q=is%3Aissue+mysql+8

**Comment by B4nan** [comment]
`4.0.0-alpha.4` is out with quite a lot of changes, main ones being #618 and #614

**Comment by kibertoad** [comment]
@gperdomor PR for knex to support mysqljs would be most welcome :)

**Comment by ALITHEALI** [comment]
Hello! Thanks for your great work on this. As today is 1st of July (based on this issue's timeline), do you think Beta can be out today? 
Many thanks.

**Comment by xeladejo** [comment]
`EntityRepository.createQueryBuilder` is it not valid in version 4?

```typescript
import { EntityRepository } from "@mikro-orm/core";
import { singleton } from "tsyringe";
import AccountEntity from "../entities/accountEntity";
import OrmClient from "../ormClient";

@singleton()
export default class AccountStore {
    private accountRepository: EntityRepository<AccountEntity>;

    public constructor(ormClient: OrmClient) {
        this.accountRepository = ormClient.em.getRepository(AccountEntity);
    }

    public findList(): void {
        const query = this.accountRepository.createQueryBuilder();

        console.log(query);
    }
}
```

> TSError: ⨯ Unable to compile TypeScript:
src/stores/accountStore.ts(23,46): error TS2339: Property 'createQueryBuilder' does not exist on type 'EntityRepository<AccountEntity>'.

PS: Since all v4 packages are new, can you publish them as `@latest` and not as `@new` even if their are alpha?

**Comment by B4nan** [comment]
`4.0.0-alpha.5` is out, with some new breaking changes (#648) and some interesting additions (#642, #645).

Also updated the [migration guide](https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/upgrading-v3-to-v4.md) with notes about the monorepo redesign.

**Comment by B4nan** [comment]
`4.0.0-alpha.6` is out, with [filters](https://github.com/mikro-orm/mikro-orm/blob/dev/docs/docs/filters.md) (#663).

**Comment by B4nan** [comment]
For nest users, I created new packaged based on the work from Dario with changes needed for v4:

https://github.com/mikro-orm/nestjs

Will publish that later this week under `@mikro-orm/nestjs`, until then you can inline it in your projects. It should solve most of the v4 issues (e.g. the `mikro-orm` meta package was needed, also the EM flavours are now registered correctly so no need for using `@Inject('EntityManager')` explicitly).

**Comment by B4nan** [comment]
`4.0.0-alpha.8` is out with some bug fixes (#683) and small refactorings. Also `@mikro-orm/nestjs` is now published to npm.

**Comment by CyriacBr** [comment]
Not sure if this is the right place to report issues about V4, but I have a few.

1) There is no validation for incorrect `type` value in the config. MikroORM throws instead an error at `Configuration.initDriver()`
2) SQLite integration seems broken. This happens after init with the sqlite driver.
``bash
 knex: Unknown configuration option 'client' value function Client_SQLite3(config) {
      Client.call(this, config);
      if (isUndefined(config.useNullAsDefault)) {
        this.logger.warn(
          'sqlite does not support inserting default values. Set the ' +
            '`useNullAsDefault` flag to hide this warning. ' +
            '(see docs http://knexjs.org/#Builder-insert).'
        );
      }
    }. Note that it is case-sensitive, check documentation for supported values.

      at Object.Knex [as default] (../../node_modules/@mikro-orm/knex/node_modules/knex/lib/knex.js:38:13)
      at SqliteConnection.createKnexClient (../../node_modules/@mikro-orm/knex/src/AbstractSqlConnection.ts:67:16)
      at SqliteConnection.connect (../../node_modules/@mikro-orm/sqlite/src/SqliteConnection.ts:12:24)
```

**Comment by B4nan** [comment]
1. In v3 it had a default value, in v4 its probably validated only at TS level. Will add a runtime validation too. 

2. It works fine in tests, how do you initialize the ORM?

**Comment by CyriacBr** [comment]
Here's the config:
```ts
export default <Options>{
  metadataProvider: TsMorphMetadataProvider,
  entities: [BaseEntity, Author, Book, Address, WithBadEnum, BookTag],
  dbName: 'test.db',
  type: 'sqlite',
  debug: true,
  cache: {
    enabled: true,
    pretty: true,
    options: { cacheDir: process.cwd() + '/test/temp' },
  },
  highlight: true,
};
```
It was working fine before I upgraded to v4. Btw it works with MySQLDriver tho.
FYI it's literally [this project](https://github.com/CyriacBr/mikro-resources/tree/develop/packages/fixtures) with mikro-orm v4 packages added and `mikro-orm` removed.

**Comment by B4nan** [comment]
`4.0.0-alpha.11` is out with type safe references! (#214, #691) 

This might be the last alpha release before we merge #515 and release first RC. After that I will focus on updating the docs.

**Comment by CyriacBr** [comment]
I am not sure about this change. The usage looks fairly unusual. Using `$` or get() this way looks fairly cumbersome. And add to that the need for the `! ` (even if justified) too and that looks like a code not too fun to write or look at.
I think the approach I mentioned to you months ago about generating proper typings during discovery and overriding MikroORM type definitions thanks to interface merging would be a better approach. This is something we could look into more if you are interested. I have a PoC working, but not tested for v4.

**Comment by B4nan** [comment]
> The usage looks fairly unusual. Using $ or get() this way looks fairly cumbersome.

We would still have to have something like `$`/`get()` even with codegen. Maybe you did not fully understand how it works - those are added on the runtime via TS, we need something like that to allow sync type safe path to the wrapped entity. Codegen would help only with preparing some types where we could easily infer what can be populated and what not - but that is working fine already without codegen (at least for `Reference` and `Collection` - we don't need it elsewhere).

> And add to that the need for the ! (even if justified) too and that looks like a code not too fun to write or look at.

Well, there is no way around this. If a property is defined as nullable, the `Loaded` type still have to keep it as nullable, as you don't know whether there is an actual entity in the db. You cannot pass this information to TS, as it is dependent on the actual data, not of the query/populate hint.

This feature is fully optional, just like the `Reference` wrapper, don't use it if you don't like it :]

> I think the approach I mentioned to you months ago about generating proper typings during discovery and overriding MikroORM type definitions thanks to interface merging would be a better approach. This is something we could look into more if you are interested. I have a PoC working, but not tested for v4.

As mentioned above, I don't believe codegen would help much here, this has to be fully dynamic. I am not really interested in codegen altogether, but if you can find a way to make it work optionally, that's a different story - still it would not help much, not with the things you mentioned here "you don't like" about this change :]. 

If you wanna continue discussion on this, please let's move it to #214.

**Comment by B4nan** [comment]
`4.0.0-rc.0` is out and #515 is now merged to master. So from now on, the development will again happen in the `master` branch. Will keep this issue open till the final release is out. If we do not hit any new roadblock, stable version could be out within 2 weeks.

Don't forget that it's still under the `next` tag on NPM, so either install `4.0.0-rc.0` explicitly, or use `@next`.

Migration guide can be now found on the website:

https://mikro-orm.io/docs/upgrading-v3-to-v4

And the `next` version in docs is now about v4. 

https://mikro-orm.io/docs/next

I made one small additional BC break in highlighting - as the `highlight.js` dependency was too fat, I developed two replacement highlighters (for SQL and mongo) that can be now used instead of it. More about this can be found in the end of the migration guide, in general highlighting is now disabled and you need to provider `highlighter` option (`highlight: boolean` is now gone).

**Comment by egodsk** [comment]
> And the `next` version in docs is now about v4.
> 
> https://mikro-orm.io/docs/next
> 
Linking directly to the `/next` does not work, return 404 :) Here is a link to the first page on the `/next` documentation:

https://mikro-orm.io/docs/next/installation

**Comment by B4nan** [comment]
`4.0.0-rc.1` is out with few smaller fixes and improvements.

https://github.com/mikro-orm/mikro-orm/compare/ba622499b...eeae2be

**Comment by B4nan** [comment]
`4.0.0-rc.2` is out with mainly performance improvements, including UoW bulk deletes (#757)

https://github.com/mikro-orm/mikro-orm/compare/eeae2be...d83f648

**Comment by endel** [comment]
Hi @B4nan, 👋  thanks a lot for your efforts on mikro-orm. I'm about to try it out for the first time!

Sorry to ask a question on this thread, I'm considering using it for a project, and noticed that you have `typescript` as a **dependency** (not dev-dependency) on all example repositories. Is that intended? Is the TypeScript API's being used during runtime for some purpose on `mikro-orm`? If so, could you explain what happens, or point me to somewhere you could've potentially already explained?

Cheers!

**Comment by B4nan** [comment]
No longer true for v4. TS is a runtime dependency of ts-morph, so as long as you use different metadata provider, it is not needed. ts-morph is also used in some CLI dependencies, namely entity generator and migrations, so be sure to also move `cli` package to dev dependencies if you don't wanna have TS in production builds.

Will need to narrow this in the examples, totally forgot to check this bit.

**Comment by B4nan** [comment]
`4.0.0-rc.3` is out, with few minor fixes and refactorings (as well as upgrade to TS 4).

https://github.com/mikro-orm/mikro-orm/compare/099f48446...8018c41db

**Comment by elendirx** [comment]
Wanted to try it out but (force cleaning cache didn't help):
```
C:\projects\cloudgarden\cleanext>npm i mikro-orm@^4.0.0-rc.4
npm ERR! code ETARGET
npm ERR! notarget No matching version found for escaya@^0.0.23.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@mikro-orm/core'
npm ERR! notarget
```
Is it just me?

**Comment by B4nan** [comment]
Looks like trying out escaya was a bad move, it works well, but this is the second time the maintainer removed published version from NPM... I will probably revert back to acorn and ship new RC later today.

Btw with yarn it kinda works, it will let you pick one of the available versions.
Btw2 - don't use `mikro-orm` package, use `@mikro-orm/core`. There were some issues due to the metapackage and peer dependencies of driver packages. The metapackage will be deprecated, or I might make it as empty package that will just force you to install its peer dependencies.

**Comment by chrisbrantley** [comment]
Any idea when this will be fixed? We had to revert back to rc-2 because of the escaya issue.

**Comment by B4nan** [comment]
I was away for last few days, will ship rc.5 today, probably with upgraded escaya - will give it one more chance, if the version will be unpublished again, I will revert to acorn. I am also finalizing internal rewrite that should speed up things a bit (no more merging entities twice) and improve how custom types are handled (so the conversion methods are not called multiple times with already converted values).

**Comment by B4nan** [comment]
`4.0.0-rc.5` is out, with fixes in QB and improved support for custom types (#800).

https://github.com/mikro-orm/mikro-orm/compare/d83c6a1...8477d4f71

**Comment by B4nan** [comment]
`4.0.0-rc.6` is out, as I realised that fixing #784 introduced quite huge BC break, so this version reverts that (hides the new behaviour behind `populateAfterFlush` config option). It also adds one small improvement - `expr` helper to allow using custom expressions with `FilterQuery` type (#802):

```ts
const books = await em.find(Book, {
  [expr('upper(title)')]: em.getKnex().raw('upper(?)', ['b2']), // no TS errors
});
```

**Comment by pigulla** [comment]
Unfortunately, migrations don't work with rc.6:

```
async up(): Promise<void> {
    this.getKnex()
}
```
fails with `TypeError: this.driver.getConnection is not a function`

**Comment by B4nan** [comment]
What does not work is this new knex getter, and execute method (that is using it), both are new additions. Migrations itself (so `addSql()`) are working just fine.

Btw I see this quite often - why do people strip the stack trace? The error message without stack trace is like having only the last page of a book :] 

Will ship the fix later today or during tomorrow, already in master (4f7c8b2a9).

As a workaround, this could work (as the issue is that connection instance was passed to migrations instead of driver):

```ts
// @ts-ignore
const knex = this.driver.getKnex();
```

**Comment by jshearer** [comment]
Hey @B4nan, I suppose this could be asked in a new issue, but it seems to be a difference between v3 and v4: What happened to the second generic parameter to `IdentifiedReference`? My primary key is a uuid called `global_id`, how do I represent that? Is the pk automatically detected now or something?

**Comment by jshearer** [comment]
Hi @B4nan, not sure if this belongs in here or a separate issue as v4 hasn't been released yet:

I'm trying out the new Single Table Inheritance feature, and encountering something I don't quite understand. My data model looks like this:

```typescript
@Entity({
    discriminatorColumn: "type",
})
export class Task extends BaseEntity {
     ...
}

@Entity({
    discriminatorValue: "report",
})
export class Report extends Task {
    @ManyToOne({ inversedBy: "reports", eager: true })
    reporter: IdentifiedReference<Reporter, "global_id">;
}

@Entity()
export class Reporter extends BaseEntity {
    @OneToMany(
        () => Report,
        report => report.reporter,
    )
    reports = new Collection<Report>(this);
}
```

But the error I get says: 
```
MetadataError: Task.reporter has wrong 'inversedBy' reference type: Report instead of Task
```

Now... I suppose I could just change `Reporter.reports` to point to `Task` instead of `Report`, but that's not really correct: only `Report` types will have a `reporter` value set, and all `Reporter.reports` should be of the specific type `Report`, not `Task` (understanding of course that Report is a subclass of Task).

What is the intended behavior here? Can discriminated single-table-inheritance types fundamentally be the target of `ManyToOne` relationships, and this is just a bug? Or am I misunderstanding the pattern?

**Comment by B4nan** [comment]
@jshearer open new issue for that, and ideally provide full reproduction. maybe we just have too strict (or buggy) validation, you could also try to disable it (comment out the bits in the ORM code) to see if things actually work fine.

**Comment by elendirx** [comment]
Thanks for your continuous support. Unfortunately it stopped working for me after updating from rc4 to rc6, I started getting:

```
MetadataError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?
    at Function.onlyAbstractEntitiesDiscovered (C:\projects\cloudgarden\cleanext\node_modules\@mikro-orm\core\utils\errors.js:130:16)
    at MetadataValidator.validateDiscovered (C:\projects\cloudgarden\cleanext\node_modules\@mikro-orm\core\metadata\MetadataValidator.js:47:41)
    at MetadataDiscovery.findEntities (C:\projects\cloudgarden\cleanext\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:67:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MetadataDiscovery.discover (C:\projects\cloudgarden\cleanext\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:32:9)
    at async Function.init (C:\projects\cloudgarden\cleanext\node_modules\@mikro-orm\core\MikroORM.js:40:24)
    at async getConnection (C:\projects\cloudgarden\cleanext\.next\server\pages\api\model.js:257:15)
    at async getGlobalContainer (C:\projects\cloudgarden\cleanext\.next\server\pages\api\model.js:352:22)
    at async getRequestScopeContainer (C:\projects\cloudgarden\cleanext\.next\server\pages\api\model.js:359:27) {
  entity: undefined,
  name: 'MetadataError'
}
```

please note that I use Next.js so my code is heavily Webpacked and Babelized. I'm using
```
metadataProvider: ReflectMetadataProvider
```

I'd be grateful for any ideas what commit could have caused it before I start digging deeper.

**Comment by B4nan** [comment]
I believe this could be fixed already (there was similar issue with babel), will be shipping rc.7 later today, if that wont help, create new issue ideally with a reproduction repo.

**Comment by B4nan** [comment]
`4.0.0-rc.7` is out, [property serializers](https://mikro-orm.io/docs/next/serializing#property-serializers) and [initial migrations](https://mikro-orm.io/docs/next/migrations#initial-migration).

https://github.com/mikro-orm/mikro-orm/compare/c6084ab2f...ddc2e2771

**Comment by elendirx** [comment]
> I believe this could be fixed already

I confirm rc7 works like a charm. Thanks!

**Comment by B4nan** [comment]
`4.0.0-rc.8` is out with a fix for one regression (219ce461) plus few smaller changes. 

https://github.com/mikro-orm/mikro-orm/compare/ddc2e2771...510629263

**Comment by B4nan** [comment]
The time has come, I just shipped the stable release of v4 🚀. Thank you all for the feedback!

https://medium.com/@b4nan/mikro-orm-4-filling-the-gaps-b1fa527624e2
https://github.com/mikro-orm/mikro-orm/releases/tag/v4.0.0
https://www.npmjs.com/package/@mikro-orm/core
